/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'HutchUK' at '8/4/15 12:53 PM' with Gradle 1.11
 *
 * @author HutchUK, @date 8/4/15 12:53 PM
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
