/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'HutchUK' at '8/4/15 12:53 PM' with Gradle 1.11
 *
 * @author HutchUK, @date 8/4/15 12:53 PM
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
